version: '3'

services:

    jenkins:
        image: jenkins/jenkins:jdk11
        container_name: jenkins
        ports:
            - "8880:8080"
            - "50000:50000"
        volumes:
            - ../volumes/jenkins:/var/jenkins_home
        networks:
            - docker_network

    ubuntu:
        build:
            context: ../dockerfiles/slave
        container_name: ubuntu
        depends_on:
            - jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - docker_network
        command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8080/computer/Slave/slave-agent.jnlp -secret 2c50b3db4cab0fe2b4ddfbf7d542e783f45101e7a41ca9ec7026acf9c398d205 -workDir "/home/"

    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        container_name: artifactory
        volumes:
            - ../volumes/artifactory:/var/opt/jfrog/artifactory
        ports:
            - "8081:8081"
            - "8082:8082"
        networks:
            - docker_network

    selenium_hub:
        image: selenium/hub
        container_name: seleniumhub
        ports:
            - "4444:4444"
        networks:
            - docker_network

    selenium_firefox:
        image: selenium/node-firefox
        container_name: firefox
        depends_on:
            - selenium_hub
        environment: 
            - HUB_HOST=seleniumhub
            - HUB_PORT=4444
        networks:
            - docker_network

networks:
    docker_network:
        driver: bridge
