---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01eg8wf4ref4r5ktk8sdz1tzpn"
    - from: "jfevt@*"
      to: "jfevt@01eg8wevhs41pa0r842ye409qt"
    - from: "jfmd@*"
      to: "jfmd@01eg8wf4q1pq54a0pj2mz045rq"
    - from: "jfrt@*"
      to: "jfrt@01eg8wfpwdd5dy0jpmfzrb12j1"
    - from: "jffe@*"
      to: "jffe@000"
licenses:
- server-name: "a434dade0936"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd09TMHlNRlF4TmpveU5qb3hNQzR4TURkYUNtbGtPaUJrT0RaaU1qSTFOUzAyT1RZMkxUUTBOR1l0\r\
    \nWW1aak1pMDBObUppWXpVM01UZGhOeklLYjNkdVpYSTZJRkJoYm1SaENuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1EZ3RNakZVTVRZNk1qWTZNVEF1TVRBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogTHNPMGF6RmQrVExQWURKZmVsSWhPbDRUREd1eVk5eE92cEFTRXRvQ2EvYTRXa2pM\r\
    \neGdJOEVHT0ZZOEJuK2hJM3FmTTBTOFhZbktweTlERzlrT29iR2tJajBMU2hLQ1NVNG9nS0dLamI2\r\
    \nUit5Y1JVa3RuM0hUcXhDWFNjRzU5S3V5U2xVSi9tNmp4eTQyLzR2RWhTdVduNWlPNlNuSnlTSnlB\r\
    \neFo5NGRQSGFwQ01VcHB5aXo0SDI5cGhuclI1WUxWQTFDcGxkaVFmNTBXL2tGSEpJVXo1aTF6WmJQ\r\
    \nMmJVZEJ0ektReTU4VHV1bHNFWGF5OUk5MlRDMVY4RHk1Z2xWMkhnamRWSlZEcDI0WUxrRC9kaUlz\r\
    \nOHg2Vk1YUzBBTDJCSVo0aDhLamxTSDBTOFY3Mmhkb2cwbWFZUmZoa1JWZllaRHN1aEVPTlFrYndG\r\
    \nUmVKSnpHdjhRPT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "2d268949e212"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TUMw\r\
    \nd09TMHlNRlF4TmpveU5qb3hNQzR4TURkYUNtbGtPaUJrT0RaaU1qSTFOUzAyT1RZMkxUUTBOR1l0\r\
    \nWW1aak1pMDBObUppWXpVM01UZGhOeklLYjNkdVpYSTZJRkJoYm1SaENuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpBdE1EZ3RNakZVTVRZNk1qWTZNVEF1TVRBM1dnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogTHNPMGF6RmQrVExQWURKZmVsSWhPbDRUREd1eVk5eE92cEFTRXRvQ2EvYTRXa2pM\r\
    \neGdJOEVHT0ZZOEJuK2hJM3FmTTBTOFhZbktweTlERzlrT29iR2tJajBMU2hLQ1NVNG9nS0dLamI2\r\
    \nUit5Y1JVa3RuM0hUcXhDWFNjRzU5S3V5U2xVSi9tNmp4eTQyLzR2RWhTdVduNWlPNlNuSnlTSnlB\r\
    \neFo5NGRQSGFwQ01VcHB5aXo0SDI5cGhuclI1WUxWQTFDcGxkaVFmNTBXL2tGSEpJVXo1aTF6WmJQ\r\
    \nMmJVZEJ0ektReTU4VHV1bHNFWGF5OUk5MlRDMVY4RHk1Z2xWMkhnamRWSlZEcDI0WUxrRC9kaUlz\r\
    \nOHg2Vk1YUzBBTDJCSVo0aDhLamxTSDBTOFY3Mmhkb2cwbWFZUmZoa1JWZllaRHN1aEVPTlFrYndG\r\
    \nUmVKSnpHdjhRPT0KdmVyc2lvbjogMQo=\r\n"
